server:
  port: 8081

spring:
  datasource:
    url: ${AGMS_MYSQL_URL:jdbc:mysql://localhost:3306/agms_iot?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${AGMS_MYSQL_USERNAME:root}
    password: ${AGMS_MYSQL_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update

agms:
  external:
    iot:
      base-url: ${AGMS_IOT_BASE_URL:http://localhost:8080/api}
      username: ${AGMS_IOT_USERNAME:agms_user}
      password: ${AGMS_IOT_PASSWORD:123456}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
